runtime: python312
entrypoint: gunicorn -b :$PORT main:app

instance_class: F4

env_variables:
  SUPABASE_URL: "https://urmhsphzfmtciybqdptw.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVybWhzcGh6Zm10Y2l5YnFkcHR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3ODgxOTcsImV4cCI6MjA4NDM2NDE5N30.f9zVtTgY0yK6ispISE62MyGmmCV5UuzXqXHonVg2cPE"
  FLASK_SECRET_KEY: "f8f7a9d6f2cba09073170d09d5dbc4e19fe816119d8f05e918f5b9d79f495c7a"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: auto
  secure: always